#!/usr/bin/env python3
"""Update SBOM.json and SBOM.md with current versions from requirements.txt.

Usage:
    python scripts/generate_sbom.py                    # Preview (dry-run)
    python scripts/generate_sbom.py --apply             # Apply changes
    python scripts/generate_sbom.py --update-deps       # Run pip-compile first, then preview
    python scripts/generate_sbom.py --update-deps --apply  # Full update

Reads:
  - requirements.txt   (all pinned runtime versions — regenerated by --update-deps)
  - pyproject.toml     (project version and dependency specs)
  - LICENSE            (SPDX license identifier)

Updates:
  - SBOM.json  components[].version, bom-ref, purl, metadata timestamp + version
  - SBOM.md    version table cells and Generated date

Workflow after changing pyproject.toml:
    python scripts/generate_sbom.py --update-deps --apply
"""

import json
import re
import shutil
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SBOM_PATH = ROOT / "SBOM.json"
SBOM_MD_PATH = ROOT / "SBOM.md"
REQUIREMENTS_PATH = ROOT / "requirements.txt"
PYPROJECT_PATH = ROOT / "pyproject.toml"
LICENSE_PATH = ROOT / "LICENSE"

MONTHS = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

# normalized package name (requirements.txt) → display name in SBOM.md tables
MD_DISPLAY_NAME: dict[str, str] = {
    "mcp": "mcp",
    "pydantic": "pydantic",
    "starlette": "starlette",
    "uvicorn": "uvicorn",
    "anyio": "anyio",
    "h11": "h11",
    "sse-starlette": "sse-starlette",
    "python-multipart": "python-multipart",
    "httpx": "httpx",
    "httpx-sse": "httpx-sse",
    "httpcore": "httpcore",
    "certifi": "certifi",
    "idna": "idna",
    "pyjwt": "pyjwt",
    "cryptography": "cryptography",
    "cffi": "cffi",
    "pycparser": "pycparser",
    "pydantic-core": "pydantic-core",
    "pydantic-settings": "pydantic-settings",
    "annotated-types": "annotated-types",
    "typing-extensions": "typing-extensions",
    "typing-inspection": "typing-inspection",
    "python-dotenv": "python-dotenv",
    "jsonschema": "jsonschema",
    "jsonschema-specifications": "jsonschema-specifications",
    "referencing": "referencing",
    "rpds-py": "rpds-py",
    "attrs": "attrs",
    "click": "click",
}


def parse_requirements(path: Path) -> dict[str, str]:
    """Parse requirements.txt → {normalized_name: version}."""
    versions: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if "==" not in line or line.startswith("#"):
            continue
        name, version = line.split("==", 1)
        name = re.sub(r"\[.*\]", "", name)  # strip extras like [crypto]
        name = name.lower().replace("_", "-")
        versions[name] = version.strip()
    return versions


def parse_pyproject_version(path: Path) -> str | None:
    """Extract version from pyproject.toml."""
    if not path.exists():
        return None
    for line in path.read_text().splitlines():
        m = re.match(r'^version\s*=\s*"([^"]+)"', line)
        if m:
            return m.group(1)
    return None


def parse_license_spdx(path: Path) -> str | None:
    """Derive SPDX identifier from the first line of LICENSE."""
    if not path.exists():
        return None
    first_line = path.read_text().splitlines()[0].upper()
    if "MIT" in first_line:
        return "MIT"
    if "APACHE" in first_line and "2" in first_line:
        return "Apache-2.0"
    if "AFFERO" in first_line and "3" in first_line:
        return "AGPL-3.0-only"
    if "GPL" in first_line and "3" in first_line:
        return "GPL-3.0-only"
    if "GPL" in first_line and "2" in first_line:
        return "GPL-2.0-only"
    return None


def update_component(
    comp: dict,
    versions: dict[str, str],
    changes: list[str],
    bom_ref_renames: dict[str, str],
) -> None:
    """Update a component's version, bom-ref, and purl in place."""
    purl = comp.get("purl", "")
    if not purl.startswith("pkg:pypi/"):
        return
    pkg_name = purl.split("/")[1].split("@")[0].lower().replace("_", "-")
    if pkg_name not in versions:
        return
    new_ver = versions[pkg_name]
    old_ver = comp["version"]
    if old_ver == new_ver:
        return

    comp["version"] = new_ver

    old_ref = comp["bom-ref"]
    if old_ref.endswith(f"-{old_ver}"):
        new_ref = old_ref[: -len(f"-{old_ver}")] + f"-{new_ver}"
    else:
        new_ref = re.sub(r"-[\d][\d.]*$", f"-{new_ver}", old_ref)
    comp["bom-ref"] = new_ref
    bom_ref_renames[old_ref] = new_ref

    comp["purl"] = re.sub(r"@[\d][\d.]*$", f"@{new_ver}", purl)
    changes.append(f"  {comp['name']}: {old_ver} → {new_ver}")


def sync_sbom_md(
    versions: dict[str, str],
    project_version: str | None,
    project_license: str | None,
    apply_mode: bool,
    now: datetime,
) -> list[str]:
    """Sync SBOM.md version cells to current package versions."""
    if not SBOM_MD_PATH.exists():
        return []

    content = SBOM_MD_PATH.read_text()
    md_changes: list[str] = []

    if project_version:
        m = re.search(r"(\*\*Version:\*\* )([\d.]+)", content)
        if m and m.group(2) != project_version:
            content = re.sub(r"(\*\*Version:\*\* )[\d.]+", r"\g<1>" + project_version, content)
            md_changes.append(f"  SBOM.md: Version {m.group(2)} → {project_version}")

    if project_license:
        m = re.search(r"(\*\*License:\*\* )(\S+)", content)
        if m and m.group(2) != project_license:
            content = re.sub(r"(\*\*License:\*\* )\S+", r"\g<1>" + project_license, content)
            md_changes.append(f"  SBOM.md: License {m.group(2)} → {project_license}")

    for pkg_name, display_name in MD_DISPLAY_NAME.items():
        new_ver = versions.get(pkg_name)
        if not new_ver:
            continue
        pattern = r"(\| " + re.escape(display_name) + r" \| )(\S+)( \| )"
        m = re.search(pattern, content)
        if m and m.group(2) != new_ver:
            old_ver = m.group(2)
            content = re.sub(pattern, r"\g<1>" + new_ver + r"\3", content)
            md_changes.append(f"  SBOM.md: {display_name} {old_ver} → {new_ver}")

    if not md_changes:
        return []

    date_str = f"{now.day}. {MONTHS[now.month - 1]} {now.year}"
    content = re.sub(r"\*\*Generated:\*\* .+", f"**Generated:** {date_str}", content)
    content = re.sub(
        r"\*\*Generation Method:\*\* .+",
        "**Generation Method:** Automated (scripts/generate_sbom.py)",
        content,
    )
    md_changes.append(f"  SBOM.md: Generated → {date_str}")

    if apply_mode:
        SBOM_MD_PATH.write_text(content)

    return md_changes


def run_pip_compile() -> None:
    """Regenerate requirements.txt and requirements-dev.txt from pyproject.toml."""
    pip_compile = shutil.which("pip-compile")
    if pip_compile is None:
        print("ERROR: pip-compile not found. Install it: pip install pip-tools")
        sys.exit(1)
    commands = [
        [
            pip_compile,
            "pyproject.toml",
            "--output-file", "requirements.txt",
            "--no-emit-options",
        ],
        [
            pip_compile,
            "pyproject.toml",
            "--extra", "dev",
            "--output-file", "requirements-dev.txt",
            "--no-emit-options",
        ],
    ]
    for cmd in commands:
        target = cmd[cmd.index("--output-file") + 1]
        print(f"  pip-compile → {target}")
        result = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"ERROR: pip-compile failed for {target}:")
            print(result.stderr)
            sys.exit(1)


def check_requirements_staleness() -> None:
    """Warn if pyproject.toml is newer than requirements.txt."""
    if not REQUIREMENTS_PATH.exists():
        return
    if PYPROJECT_PATH.stat().st_mtime > REQUIREMENTS_PATH.stat().st_mtime:
        print(
            "WARNING: pyproject.toml is newer than requirements.txt. "
            "Run with --update-deps to regenerate first."
        )


def main() -> None:
    apply_mode = "--apply" in sys.argv
    update_deps = "--update-deps" in sys.argv

    for path in (SBOM_PATH, REQUIREMENTS_PATH if not update_deps else PYPROJECT_PATH):
        if not path.exists():
            print(f"ERROR: {path} not found")
            sys.exit(1)

    if update_deps:
        print("Running pip-compile to regenerate requirements files...")
        run_pip_compile()
        print()
    else:
        check_requirements_staleness()

    sbom = json.loads(SBOM_PATH.read_text())
    versions = parse_requirements(REQUIREMENTS_PATH)
    project_version = parse_pyproject_version(PYPROJECT_PATH)
    project_license = parse_license_spdx(LICENSE_PATH)

    changes: list[str] = []
    bom_ref_renames: dict[str, str] = {}

    for comp in sbom.get("components", []):
        update_component(comp, versions, changes, bom_ref_renames)

    # Update dependency-graph refs when bom-refs changed
    for dep in sbom.get("dependencies", []):
        dep["dependsOn"] = [bom_ref_renames.get(ref, ref) for ref in dep.get("dependsOn", [])]

    now = datetime.now(UTC)
    md_changes = sync_sbom_md(versions, project_version, project_license, apply_mode, now)

    if not changes and not md_changes:
        print("✓ SBOM.json and SBOM.md are up to date. No changes needed.")
        return

    if changes:
        timestamp = now.strftime("%Y-%m-%dT%H:%M:%SZ")
        sbom["metadata"]["timestamp"] = timestamp
        old_version = sbom.get("version", 1)
        sbom["version"] = old_version + 1
        changes.append(f"  Meta: SBOM version {old_version} → {sbom['version']}")
        changes.append(f"  Meta: timestamp → {timestamp}")

    all_changes = changes + md_changes
    print(f"{'APPLYING' if apply_mode else 'PREVIEW'}: {len(all_changes)} change(s):")
    for c in all_changes:
        print(c)

    if apply_mode:
        if changes:
            SBOM_PATH.write_text(json.dumps(sbom, indent=2, ensure_ascii=False) + "\n")
        targets = (["SBOM.json"] if changes else []) + (["SBOM.md"] if md_changes else [])
        print(f"\n✓ Updated: {' + '.join(targets)}")
    else:
        targets = (["SBOM.json"] if changes else []) + (["SBOM.md"] if md_changes else [])
        print(f"\nRun with --apply to write changes to {' and '.join(targets)}")


if __name__ == "__main__":
    main()
